package voxgig.elementdemosdk.core;

import java.util.Map;

import voxgig.elementdemosdk.utility.Json;

/** Static SDK configuration and by-name feature construction. */
@SuppressWarnings({"unchecked"})
public final class Config {

  private Config() {}

  public static Map<String, Object> makeConfig() {
    return (Map<String, Object>) Json.parse(configJson());
  }

  // SHARED CONFIG (sdkgen rung L2).
  //
  // The SDK reads the config on every request and never writes to it, so one
  // instance is shared by every client rather than rebuilt per client - the
  // difference between parsing the embedded JSON once and once per client.
  //
  // Initialization-on-demand holder: the JLS guarantees the class initializer
  // runs once, lazily, and safely under concurrency, with no locking on the
  // read path.
  private static final class SharedHolder {
    static final Map<String, Object> VALUE = makeConfig();
  }

  // The process-wide config, built once on first use.
  //
  // The returned map is SHARED: treat it as read-only. Callers that need to
  // mutate should use makeConfig, which always parses a fresh copy.
  public static Map<String, Object> sharedConfig() {
    return SharedHolder.VALUE;
  }

  public static Feature makeFeature(String name) {
    switch (name) {
      case "elementcard":
        return new voxgig.elementdemosdk.feature.ElementcardFeature();
      case "retry":
        return new voxgig.elementdemosdk.feature.RetryFeature();
      case "test":
        return new voxgig.elementdemosdk.feature.TestFeature();
      case "timeout":
        return new voxgig.elementdemosdk.feature.TimeoutFeature();
      default:
        return new voxgig.elementdemosdk.feature.BaseFeature();
    }
  }

  private static String configJson() {
    StringBuilder b = new StringBuilder();
    b.append("{");
    b.append(" \"main\": {");
    b.append("  \"name\": \"Elementdemo\",");
    b.append("  \"slug\": \"elementdemo\",");
    b.append("  \"version\": \"0.1.0\",");
    b.append("  \"target\": \"java\"");
    b.append(" },");
    b.append(" \"feature\": {");
    b.append("  \"elementcard\": {");
    b.append("   \"options\": {");
    b.append("    \"active\": false,");
    b.append("    \"print\": false");
    b.append("   },");
    b.append("   \"transport\": \"none\"");
    b.append("  },");
    b.append("  \"retry\": {");
    b.append("   \"options\": {");
    b.append("    \"active\": false,");
    b.append("    \"factor\": 2,");
    b.append("    \"maxDelay\": 2000,");
    b.append("    \"minDelay\": 50,");
    b.append("    \"retries\": 2,");
    b.append("    \"statuses\": [");
    b.append("     408,");
    b.append("     425,");
    b.append("     429,");
    b.append("     500,");
    b.append("     502,");
    b.append("     503,");
    b.append("     504");
    b.append("    ]");
    b.append("   },");
    b.append("   \"transport\": \"wrap\"");
    b.append("  },");
    b.append("  \"test\": {");
    b.append("   \"options\": {");
    b.append("    \"active\": false");
    b.append("   },");
    b.append("   \"transport\": \"base\"");
    b.append("  },");
    b.append("  \"timeout\": {");
    b.append("   \"options\": {");
    b.append("    \"active\": false,");
    b.append("    \"ms\": 30000");
    b.append("   },");
    b.append("   \"transport\": \"wrap\"");
    b.append("  }");
    b.append(" },");
    b.append(" \"options\": {");
    b.append("  \"base\": \"http://localhost:8902/api/{account_id}\",");
    b.append("  \"server\": {");
    b.append("   \"account_id\": \"\"");
    b.append("  },");
    b.append("  \"auth\": {");
    b.append("   \"prefix\": \"Bearer\"");
    b.append("  },");
    b.append("  \"headers\": {");
    b.append("   \"content-type\": \"application/json\"");
    b.append("  },");
    b.append("  \"entity\": {");
    b.append("   \"element\": {},");
    b.append("   \"group\": {},");
    b.append("   \"isotope\": {},");
    b.append("   \"series\": {}");
    b.append("  }");
    b.append(" },");
    b.append(" \"entity\": {");
    b.append("  \"element\": {");
    b.append("   \"fields\": [");
    b.append("    {");
    b.append("     \"name\": \"block\",");
    b.append("     \"req\": true,");
    b.append("     \"short\": \"Orbital block, one of s, p, d, f.\",");
    b.append("     \"type\": \"`$STRING`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"charge\",");
    b.append("     \"type\": \"`$INTEGER`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"discovered\",");
    b.append("     \"short\": \"Year of discovery, absent for elements known since antiquity.\",");
    b.append("     \"type\": \"`$INTEGER`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"group\",");
    b.append("     \"short\": \"Periodic table column, 1 to 18, absent for the f-block.\",");
    b.append("     \"type\": \"`$INTEGER`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"id\",");
    b.append("     \"req\": true,");
    b.append("     \"short\": \"Element identifier, the lowercase symbol.\",");
    b.append("     \"type\": \"`$STRING`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"ion\",");
    b.append("     \"type\": \"`$STRING`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"mass\",");
    b.append("     \"req\": true,");
    b.append("     \"short\": \"Standard atomic weight in daltons.\",");
    b.append("     \"type\": \"`$NUMBER`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"name\",");
    b.append("     \"req\": true,");
    b.append("     \"short\": \"Element name.\",");
    b.append("     \"type\": \"`$STRING`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"number\",");
    b.append("     \"req\": true,");
    b.append("     \"short\": \"Atomic number.\",");
    b.append("     \"type\": \"`$INTEGER`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"ok\",");
    b.append("     \"type\": \"`$BOOLEAN`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"period\",");
    b.append("     \"req\": true,");
    b.append("     \"short\": \"Periodic table row, 1 to 7.\",");
    b.append("     \"type\": \"`$INTEGER`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"phase\",");
    b.append("     \"short\": \"Phase at standard temperature and pressure.\",");
    b.append("     \"type\": \"`$STRING`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"series_id\",");
    b.append("     \"req\": true,");
    b.append("     \"short\": \"Chemical series this element belongs to.\",");
    b.append("     \"type\": \"`$STRING`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"symbol\",");
    b.append("     \"req\": true,");
    b.append("     \"short\": \"Chemical symbol.\",");
    b.append("     \"type\": \"`$STRING`\"");
    b.append("    }");
    b.append("   ],");
    b.append("   \"name\": \"element\",");
    b.append("   \"op\": {");
    b.append("    \"create\": {");
    b.append("     \"input\": \"data\",");
    b.append("     \"name\": \"create\",");
    b.append("     \"points\": [");
    b.append("      {");
    b.append("       \"args\": {");
    b.append("        \"params\": [");
    b.append("         {");
    b.append("          \"kind\": \"param\",");
    b.append("          \"name\": \"id\",");
    b.append("          \"orig\": \"element_id\",");
    b.append("          \"reqd\": true,");
    b.append("          \"type\": \"`$STRING`\"");
    b.append("         }");
    b.append("        ]");
    b.append("       },");
    b.append("       \"kind\": \"http\",");
    b.append("       \"method\": \"POST\",");
    b.append("       \"orig\": \"/element/{element_id}/ionize\",");
    b.append("       \"parts\": [");
    b.append("        \"element\",");
    b.append("        \"{id}\",");
    b.append("        \"ionize\"");
    b.append("       ],");
    b.append("       \"rename\": {");
    b.append("        \"param\": {");
    b.append("         \"element_id\": \"id\"");
    b.append("        }");
    b.append("       },");
    b.append("       \"segments\": [");
    b.append("        {");
    b.append("         \"lit\": \"element\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"var\": \"id\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"lit\": \"ionize\"");
    b.append("        }");
    b.append("       ],");
    b.append("       \"select\": {");
    b.append("        \"$action\": \"ionize\",");
    b.append("        \"exist\": [");
    b.append("         \"id\"");
    b.append("        ]");
    b.append("       },");
    b.append("       \"transform\": {");
    b.append("        \"req\": \"`reqdata`\",");
    b.append("        \"res\": \"`body`\"");
    b.append("       }");
    b.append("      },");
    b.append("      {");
    b.append("       \"args\": {},");
    b.append("       \"kind\": \"http\",");
    b.append("       \"method\": \"POST\",");
    b.append("       \"orig\": \"/element\",");
    b.append("       \"parts\": [");
    b.append("        \"element\"");
    b.append("       ],");
    b.append("       \"segments\": [");
    b.append("        {");
    b.append("         \"lit\": \"element\"");
    b.append("        }");
    b.append("       ],");
    b.append("       \"select\": {},");
    b.append("       \"transform\": {");
    b.append("        \"req\": \"`reqdata`\",");
    b.append("        \"res\": \"`body`\"");
    b.append("       }");
    b.append("      }");
    b.append("     ]");
    b.append("    },");
    b.append("    \"list\": {");
    b.append("     \"input\": \"data\",");
    b.append("     \"name\": \"list\",");
    b.append("     \"points\": [");
    b.append("      {");
    b.append("       \"args\": {},");
    b.append("       \"kind\": \"http\",");
    b.append("       \"method\": \"GET\",");
    b.append("       \"orig\": \"/element\",");
    b.append("       \"parts\": [");
    b.append("        \"element\"");
    b.append("       ],");
    b.append("       \"segments\": [");
    b.append("        {");
    b.append("         \"lit\": \"element\"");
    b.append("        }");
    b.append("       ],");
    b.append("       \"select\": {},");
    b.append("       \"transform\": {");
    b.append("        \"req\": \"`reqdata`\",");
    b.append("        \"res\": \"`body`\"");
    b.append("       }");
    b.append("      }");
    b.append("     ]");
    b.append("    },");
    b.append("    \"load\": {");
    b.append("     \"input\": \"data\",");
    b.append("     \"name\": \"load\",");
    b.append("     \"points\": [");
    b.append("      {");
    b.append("       \"args\": {");
    b.append("        \"params\": [");
    b.append("         {");
    b.append("          \"kind\": \"param\",");
    b.append("          \"name\": \"id\",");
    b.append("          \"orig\": \"element_id\",");
    b.append("          \"reqd\": true,");
    b.append("          \"type\": \"`$STRING`\"");
    b.append("         }");
    b.append("        ]");
    b.append("       },");
    b.append("       \"kind\": \"http\",");
    b.append("       \"method\": \"GET\",");
    b.append("       \"orig\": \"/element/{element_id}\",");
    b.append("       \"parts\": [");
    b.append("        \"element\",");
    b.append("        \"{id}\"");
    b.append("       ],");
    b.append("       \"rename\": {");
    b.append("        \"param\": {");
    b.append("         \"element_id\": \"id\"");
    b.append("        }");
    b.append("       },");
    b.append("       \"segments\": [");
    b.append("        {");
    b.append("         \"lit\": \"element\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"var\": \"id\"");
    b.append("        }");
    b.append("       ],");
    b.append("       \"select\": {");
    b.append("        \"exist\": [");
    b.append("         \"id\"");
    b.append("        ]");
    b.append("       },");
    b.append("       \"transform\": {");
    b.append("        \"req\": \"`reqdata`\",");
    b.append("        \"res\": \"`body`\"");
    b.append("       }");
    b.append("      }");
    b.append("     ]");
    b.append("    },");
    b.append("    \"remove\": {");
    b.append("     \"input\": \"data\",");
    b.append("     \"name\": \"remove\",");
    b.append("     \"points\": [");
    b.append("      {");
    b.append("       \"args\": {");
    b.append("        \"params\": [");
    b.append("         {");
    b.append("          \"kind\": \"param\",");
    b.append("          \"name\": \"id\",");
    b.append("          \"orig\": \"element_id\",");
    b.append("          \"reqd\": true,");
    b.append("          \"type\": \"`$STRING`\"");
    b.append("         }");
    b.append("        ]");
    b.append("       },");
    b.append("       \"kind\": \"http\",");
    b.append("       \"method\": \"DELETE\",");
    b.append("       \"orig\": \"/element/{element_id}\",");
    b.append("       \"parts\": [");
    b.append("        \"element\",");
    b.append("        \"{id}\"");
    b.append("       ],");
    b.append("       \"rename\": {");
    b.append("        \"param\": {");
    b.append("         \"element_id\": \"id\"");
    b.append("        }");
    b.append("       },");
    b.append("       \"segments\": [");
    b.append("        {");
    b.append("         \"lit\": \"element\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"var\": \"id\"");
    b.append("        }");
    b.append("       ],");
    b.append("       \"select\": {");
    b.append("        \"exist\": [");
    b.append("         \"id\"");
    b.append("        ]");
    b.append("       },");
    b.append("       \"transform\": {");
    b.append("        \"req\": \"`reqdata`\",");
    b.append("        \"res\": \"`body`\"");
    b.append("       }");
    b.append("      }");
    b.append("     ]");
    b.append("    },");
    b.append("    \"update\": {");
    b.append("     \"input\": \"data\",");
    b.append("     \"name\": \"update\",");
    b.append("     \"points\": [");
    b.append("      {");
    b.append("       \"args\": {");
    b.append("        \"params\": [");
    b.append("         {");
    b.append("          \"kind\": \"param\",");
    b.append("          \"name\": \"id\",");
    b.append("          \"orig\": \"element_id\",");
    b.append("          \"reqd\": true,");
    b.append("          \"type\": \"`$STRING`\"");
    b.append("         }");
    b.append("        ]");
    b.append("       },");
    b.append("       \"kind\": \"http\",");
    b.append("       \"method\": \"PUT\",");
    b.append("       \"orig\": \"/element/{element_id}\",");
    b.append("       \"parts\": [");
    b.append("        \"element\",");
    b.append("        \"{id}\"");
    b.append("       ],");
    b.append("       \"rename\": {");
    b.append("        \"param\": {");
    b.append("         \"element_id\": \"id\"");
    b.append("        }");
    b.append("       },");
    b.append("       \"segments\": [");
    b.append("        {");
    b.append("         \"lit\": \"element\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"var\": \"id\"");
    b.append("        }");
    b.append("       ],");
    b.append("       \"select\": {");
    b.append("        \"exist\": [");
    b.append("         \"id\"");
    b.append("        ]");
    b.append("       },");
    b.append("       \"transform\": {");
    b.append("        \"req\": \"`reqdata`\",");
    b.append("        \"res\": \"`body`\"");
    b.append("       }");
    b.append("      }");
    b.append("     ]");
    b.append("    }");
    b.append("   },");
    b.append("   \"relations\": {");
    b.append("    \"ancestors\": []");
    b.append("   }");
    b.append("  },");
    b.append("  \"group\": {");
    b.append("   \"fields\": [");
    b.append("    {");
    b.append("     \"name\": \"cas\",");
    b.append("     \"req\": true,");
    b.append("     \"short\": \"CAS group designation.\",");
    b.append("     \"type\": \"`$STRING`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"id\",");
    b.append("     \"req\": true,");
    b.append("     \"short\": \"Group identifier, g1 to g18.\",");
    b.append("     \"type\": \"`$STRING`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"name\",");
    b.append("     \"short\": \"Trivial name, where one exists.\",");
    b.append("     \"type\": \"`$STRING`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"number\",");
    b.append("     \"req\": true,");
    b.append("     \"short\": \"Group number, 1 to 18.\",");
    b.append("     \"type\": \"`$INTEGER`\"");
    b.append("    }");
    b.append("   ],");
    b.append("   \"name\": \"group\",");
    b.append("   \"op\": {");
    b.append("    \"list\": {");
    b.append("     \"input\": \"data\",");
    b.append("     \"name\": \"list\",");
    b.append("     \"points\": [");
    b.append("      {");
    b.append("       \"args\": {},");
    b.append("       \"kind\": \"http\",");
    b.append("       \"method\": \"GET\",");
    b.append("       \"orig\": \"/group\",");
    b.append("       \"parts\": [");
    b.append("        \"group\"");
    b.append("       ],");
    b.append("       \"segments\": [");
    b.append("        {");
    b.append("         \"lit\": \"group\"");
    b.append("        }");
    b.append("       ],");
    b.append("       \"select\": {},");
    b.append("       \"transform\": {");
    b.append("        \"req\": \"`reqdata`\",");
    b.append("        \"res\": \"`body`\"");
    b.append("       }");
    b.append("      }");
    b.append("     ]");
    b.append("    },");
    b.append("    \"load\": {");
    b.append("     \"input\": \"data\",");
    b.append("     \"name\": \"load\",");
    b.append("     \"points\": [");
    b.append("      {");
    b.append("       \"args\": {");
    b.append("        \"params\": [");
    b.append("         {");
    b.append("          \"kind\": \"param\",");
    b.append("          \"name\": \"id\",");
    b.append("          \"orig\": \"group_id\",");
    b.append("          \"reqd\": true,");
    b.append("          \"type\": \"`$STRING`\"");
    b.append("         }");
    b.append("        ]");
    b.append("       },");
    b.append("       \"kind\": \"http\",");
    b.append("       \"method\": \"GET\",");
    b.append("       \"orig\": \"/group/{group_id}\",");
    b.append("       \"parts\": [");
    b.append("        \"group\",");
    b.append("        \"{id}\"");
    b.append("       ],");
    b.append("       \"rename\": {");
    b.append("        \"param\": {");
    b.append("         \"group_id\": \"id\"");
    b.append("        }");
    b.append("       },");
    b.append("       \"segments\": [");
    b.append("        {");
    b.append("         \"lit\": \"group\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"var\": \"id\"");
    b.append("        }");
    b.append("       ],");
    b.append("       \"select\": {");
    b.append("        \"exist\": [");
    b.append("         \"id\"");
    b.append("        ]");
    b.append("       },");
    b.append("       \"transform\": {");
    b.append("        \"req\": \"`reqdata`\",");
    b.append("        \"res\": \"`body`\"");
    b.append("       }");
    b.append("      }");
    b.append("     ]");
    b.append("    }");
    b.append("   },");
    b.append("   \"relations\": {");
    b.append("    \"ancestors\": []");
    b.append("   }");
    b.append("  },");
    b.append("  \"isotope\": {");
    b.append("   \"fields\": [");
    b.append("    {");
    b.append("     \"name\": \"abundance\",");
    b.append("     \"short\": \"Natural abundance as a fraction, absent for synthetic isotopes.\",");
    b.append("     \"type\": \"`$NUMBER`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"element_id\",");
    b.append("     \"req\": true,");
    b.append("     \"short\": \"Parent element identifier.\",");
    b.append("     \"type\": \"`$STRING`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"halflife\",");
    b.append("     \"short\": \"Half-life, absent for stable isotopes.\",");
    b.append("     \"type\": \"`$STRING`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"id\",");
    b.append("     \"req\": true,");
    b.append("     \"short\": \"Isotope identifier, symbol dash mass number.\",");
    b.append("     \"type\": \"`$STRING`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"mass\",");
    b.append("     \"req\": true,");
    b.append("     \"short\": \"Isotopic mass in daltons.\",");
    b.append("     \"type\": \"`$NUMBER`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"mass_number\",");
    b.append("     \"req\": true,");
    b.append("     \"short\": \"Total protons and neutrons.\",");
    b.append("     \"type\": \"`$INTEGER`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"mode\",");
    b.append("     \"short\": \"Primary decay mode, absent for stable isotopes.\",");
    b.append("     \"type\": \"`$STRING`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"name\",");
    b.append("     \"req\": true,");
    b.append("     \"short\": \"Isotope name.\",");
    b.append("     \"type\": \"`$STRING`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"ok\",");
    b.append("     \"type\": \"`$BOOLEAN`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"product\",");
    b.append("     \"short\": \"Primary decay product isotope, absent for stable isotopes.\",");
    b.append("     \"type\": \"`$STRING`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"stable\",");
    b.append("     \"req\": true,");
    b.append("     \"short\": \"True if the isotope is stable.\",");
    b.append("     \"type\": \"`$BOOLEAN`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"steps\",");
    b.append("     \"type\": \"`$INTEGER`\"");
    b.append("    }");
    b.append("   ],");
    b.append("   \"name\": \"isotope\",");
    b.append("   \"op\": {");
    b.append("    \"create\": {");
    b.append("     \"input\": \"data\",");
    b.append("     \"name\": \"create\",");
    b.append("     \"points\": [");
    b.append("      {");
    b.append("       \"args\": {");
    b.append("        \"params\": [");
    b.append("         {");
    b.append("          \"kind\": \"param\",");
    b.append("          \"name\": \"element_id\",");
    b.append("          \"orig\": \"element_id\",");
    b.append("          \"reqd\": true,");
    b.append("          \"type\": \"`$STRING`\"");
    b.append("         },");
    b.append("         {");
    b.append("          \"kind\": \"param\",");
    b.append("          \"name\": \"id\",");
    b.append("          \"orig\": \"isotope_id\",");
    b.append("          \"reqd\": true,");
    b.append("          \"type\": \"`$STRING`\"");
    b.append("         }");
    b.append("        ]");
    b.append("       },");
    b.append("       \"kind\": \"http\",");
    b.append("       \"method\": \"POST\",");
    b.append("       \"orig\": \"/element/{element_id}/isotope/{isotope_id}/decay\",");
    b.append("       \"parts\": [");
    b.append("        \"element\",");
    b.append("        \"{element_id}\",");
    b.append("        \"isotope\",");
    b.append("        \"{id}\",");
    b.append("        \"decay\"");
    b.append("       ],");
    b.append("       \"rename\": {");
    b.append("        \"param\": {");
    b.append("         \"isotope_id\": \"id\"");
    b.append("        }");
    b.append("       },");
    b.append("       \"segments\": [");
    b.append("        {");
    b.append("         \"lit\": \"element\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"var\": \"element_id\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"lit\": \"isotope\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"var\": \"id\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"lit\": \"decay\"");
    b.append("        }");
    b.append("       ],");
    b.append("       \"select\": {");
    b.append("        \"$action\": \"decay\",");
    b.append("        \"exist\": [");
    b.append("         \"element_id\",");
    b.append("         \"id\"");
    b.append("        ]");
    b.append("       },");
    b.append("       \"transform\": {");
    b.append("        \"req\": \"`reqdata`\",");
    b.append("        \"res\": \"`body`\"");
    b.append("       }");
    b.append("      },");
    b.append("      {");
    b.append("       \"args\": {");
    b.append("        \"params\": [");
    b.append("         {");
    b.append("          \"kind\": \"param\",");
    b.append("          \"name\": \"element_id\",");
    b.append("          \"orig\": \"element_id\",");
    b.append("          \"reqd\": true,");
    b.append("          \"type\": \"`$STRING`\"");
    b.append("         }");
    b.append("        ]");
    b.append("       },");
    b.append("       \"kind\": \"http\",");
    b.append("       \"method\": \"POST\",");
    b.append("       \"orig\": \"/element/{element_id}/isotope\",");
    b.append("       \"parts\": [");
    b.append("        \"element\",");
    b.append("        \"{element_id}\",");
    b.append("        \"isotope\"");
    b.append("       ],");
    b.append("       \"segments\": [");
    b.append("        {");
    b.append("         \"lit\": \"element\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"var\": \"element_id\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"lit\": \"isotope\"");
    b.append("        }");
    b.append("       ],");
    b.append("       \"select\": {");
    b.append("        \"exist\": [");
    b.append("         \"element_id\"");
    b.append("        ]");
    b.append("       },");
    b.append("       \"transform\": {");
    b.append("        \"req\": \"`reqdata`\",");
    b.append("        \"res\": \"`body`\"");
    b.append("       }");
    b.append("      }");
    b.append("     ]");
    b.append("    },");
    b.append("    \"list\": {");
    b.append("     \"input\": \"data\",");
    b.append("     \"name\": \"list\",");
    b.append("     \"points\": [");
    b.append("      {");
    b.append("       \"args\": {");
    b.append("        \"params\": [");
    b.append("         {");
    b.append("          \"kind\": \"param\",");
    b.append("          \"name\": \"element_id\",");
    b.append("          \"orig\": \"element_id\",");
    b.append("          \"reqd\": true,");
    b.append("          \"type\": \"`$STRING`\"");
    b.append("         }");
    b.append("        ]");
    b.append("       },");
    b.append("       \"kind\": \"http\",");
    b.append("       \"method\": \"GET\",");
    b.append("       \"orig\": \"/element/{element_id}/isotope\",");
    b.append("       \"parts\": [");
    b.append("        \"element\",");
    b.append("        \"{element_id}\",");
    b.append("        \"isotope\"");
    b.append("       ],");
    b.append("       \"segments\": [");
    b.append("        {");
    b.append("         \"lit\": \"element\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"var\": \"element_id\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"lit\": \"isotope\"");
    b.append("        }");
    b.append("       ],");
    b.append("       \"select\": {");
    b.append("        \"exist\": [");
    b.append("         \"element_id\"");
    b.append("        ]");
    b.append("       },");
    b.append("       \"transform\": {");
    b.append("        \"req\": \"`reqdata`\",");
    b.append("        \"res\": \"`body`\"");
    b.append("       }");
    b.append("      }");
    b.append("     ]");
    b.append("    },");
    b.append("    \"load\": {");
    b.append("     \"input\": \"data\",");
    b.append("     \"name\": \"load\",");
    b.append("     \"points\": [");
    b.append("      {");
    b.append("       \"args\": {");
    b.append("        \"params\": [");
    b.append("         {");
    b.append("          \"kind\": \"param\",");
    b.append("          \"name\": \"element_id\",");
    b.append("          \"orig\": \"element_id\",");
    b.append("          \"reqd\": true,");
    b.append("          \"type\": \"`$STRING`\"");
    b.append("         },");
    b.append("         {");
    b.append("          \"kind\": \"param\",");
    b.append("          \"name\": \"id\",");
    b.append("          \"orig\": \"isotope_id\",");
    b.append("          \"reqd\": true,");
    b.append("          \"type\": \"`$STRING`\"");
    b.append("         }");
    b.append("        ]");
    b.append("       },");
    b.append("       \"kind\": \"http\",");
    b.append("       \"method\": \"GET\",");
    b.append("       \"orig\": \"/element/{element_id}/isotope/{isotope_id}\",");
    b.append("       \"parts\": [");
    b.append("        \"element\",");
    b.append("        \"{element_id}\",");
    b.append("        \"isotope\",");
    b.append("        \"{id}\"");
    b.append("       ],");
    b.append("       \"rename\": {");
    b.append("        \"param\": {");
    b.append("         \"isotope_id\": \"id\"");
    b.append("        }");
    b.append("       },");
    b.append("       \"segments\": [");
    b.append("        {");
    b.append("         \"lit\": \"element\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"var\": \"element_id\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"lit\": \"isotope\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"var\": \"id\"");
    b.append("        }");
    b.append("       ],");
    b.append("       \"select\": {");
    b.append("        \"exist\": [");
    b.append("         \"element_id\",");
    b.append("         \"id\"");
    b.append("        ]");
    b.append("       },");
    b.append("       \"transform\": {");
    b.append("        \"req\": \"`reqdata`\",");
    b.append("        \"res\": \"`body`\"");
    b.append("       }");
    b.append("      }");
    b.append("     ]");
    b.append("    },");
    b.append("    \"remove\": {");
    b.append("     \"input\": \"data\",");
    b.append("     \"name\": \"remove\",");
    b.append("     \"points\": [");
    b.append("      {");
    b.append("       \"args\": {");
    b.append("        \"params\": [");
    b.append("         {");
    b.append("          \"kind\": \"param\",");
    b.append("          \"name\": \"element_id\",");
    b.append("          \"orig\": \"element_id\",");
    b.append("          \"reqd\": true,");
    b.append("          \"type\": \"`$STRING`\"");
    b.append("         },");
    b.append("         {");
    b.append("          \"kind\": \"param\",");
    b.append("          \"name\": \"id\",");
    b.append("          \"orig\": \"isotope_id\",");
    b.append("          \"reqd\": true,");
    b.append("          \"type\": \"`$STRING`\"");
    b.append("         }");
    b.append("        ]");
    b.append("       },");
    b.append("       \"kind\": \"http\",");
    b.append("       \"method\": \"DELETE\",");
    b.append("       \"orig\": \"/element/{element_id}/isotope/{isotope_id}\",");
    b.append("       \"parts\": [");
    b.append("        \"element\",");
    b.append("        \"{element_id}\",");
    b.append("        \"isotope\",");
    b.append("        \"{id}\"");
    b.append("       ],");
    b.append("       \"rename\": {");
    b.append("        \"param\": {");
    b.append("         \"isotope_id\": \"id\"");
    b.append("        }");
    b.append("       },");
    b.append("       \"segments\": [");
    b.append("        {");
    b.append("         \"lit\": \"element\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"var\": \"element_id\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"lit\": \"isotope\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"var\": \"id\"");
    b.append("        }");
    b.append("       ],");
    b.append("       \"select\": {");
    b.append("        \"exist\": [");
    b.append("         \"element_id\",");
    b.append("         \"id\"");
    b.append("        ]");
    b.append("       },");
    b.append("       \"transform\": {");
    b.append("        \"req\": \"`reqdata`\",");
    b.append("        \"res\": \"`body`\"");
    b.append("       }");
    b.append("      }");
    b.append("     ]");
    b.append("    },");
    b.append("    \"update\": {");
    b.append("     \"input\": \"data\",");
    b.append("     \"name\": \"update\",");
    b.append("     \"points\": [");
    b.append("      {");
    b.append("       \"args\": {");
    b.append("        \"params\": [");
    b.append("         {");
    b.append("          \"kind\": \"param\",");
    b.append("          \"name\": \"element_id\",");
    b.append("          \"orig\": \"element_id\",");
    b.append("          \"reqd\": true,");
    b.append("          \"type\": \"`$STRING`\"");
    b.append("         },");
    b.append("         {");
    b.append("          \"kind\": \"param\",");
    b.append("          \"name\": \"id\",");
    b.append("          \"orig\": \"isotope_id\",");
    b.append("          \"reqd\": true,");
    b.append("          \"type\": \"`$STRING`\"");
    b.append("         }");
    b.append("        ]");
    b.append("       },");
    b.append("       \"kind\": \"http\",");
    b.append("       \"method\": \"PUT\",");
    b.append("       \"orig\": \"/element/{element_id}/isotope/{isotope_id}\",");
    b.append("       \"parts\": [");
    b.append("        \"element\",");
    b.append("        \"{element_id}\",");
    b.append("        \"isotope\",");
    b.append("        \"{id}\"");
    b.append("       ],");
    b.append("       \"rename\": {");
    b.append("        \"param\": {");
    b.append("         \"isotope_id\": \"id\"");
    b.append("        }");
    b.append("       },");
    b.append("       \"segments\": [");
    b.append("        {");
    b.append("         \"lit\": \"element\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"var\": \"element_id\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"lit\": \"isotope\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"var\": \"id\"");
    b.append("        }");
    b.append("       ],");
    b.append("       \"select\": {");
    b.append("        \"exist\": [");
    b.append("         \"element_id\",");
    b.append("         \"id\"");
    b.append("        ]");
    b.append("       },");
    b.append("       \"transform\": {");
    b.append("        \"req\": \"`reqdata`\",");
    b.append("        \"res\": \"`body`\"");
    b.append("       }");
    b.append("      }");
    b.append("     ]");
    b.append("    }");
    b.append("   },");
    b.append("   \"relations\": {");
    b.append("    \"ancestors\": [");
    b.append("     [");
    b.append("      \"element\"");
    b.append("     ]");
    b.append("    ]");
    b.append("   }");
    b.append("  },");
    b.append("  \"series\": {");
    b.append("   \"fields\": [");
    b.append("    {");
    b.append("     \"name\": \"color\",");
    b.append("     \"req\": true,");
    b.append("     \"short\": \"Display color used by the element card renderer.\",");
    b.append("     \"type\": \"`$STRING`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"description\",");
    b.append("     \"req\": true,");
    b.append("     \"short\": \"One-line description of the series.\",");
    b.append("     \"type\": \"`$STRING`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"id\",");
    b.append("     \"req\": true,");
    b.append("     \"short\": \"Series identifier.\",");
    b.append("     \"type\": \"`$STRING`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"name\",");
    b.append("     \"req\": true,");
    b.append("     \"short\": \"Series name.\",");
    b.append("     \"type\": \"`$STRING`\"");
    b.append("    }");
    b.append("   ],");
    b.append("   \"name\": \"series\",");
    b.append("   \"op\": {");
    b.append("    \"list\": {");
    b.append("     \"input\": \"data\",");
    b.append("     \"name\": \"list\",");
    b.append("     \"points\": [");
    b.append("      {");
    b.append("       \"args\": {},");
    b.append("       \"kind\": \"http\",");
    b.append("       \"method\": \"GET\",");
    b.append("       \"orig\": \"/series\",");
    b.append("       \"parts\": [");
    b.append("        \"series\"");
    b.append("       ],");
    b.append("       \"segments\": [");
    b.append("        {");
    b.append("         \"lit\": \"series\"");
    b.append("        }");
    b.append("       ],");
    b.append("       \"select\": {},");
    b.append("       \"transform\": {");
    b.append("        \"req\": \"`reqdata`\",");
    b.append("        \"res\": \"`body`\"");
    b.append("       }");
    b.append("      }");
    b.append("     ]");
    b.append("    },");
    b.append("    \"load\": {");
    b.append("     \"input\": \"data\",");
    b.append("     \"name\": \"load\",");
    b.append("     \"points\": [");
    b.append("      {");
    b.append("       \"args\": {");
    b.append("        \"params\": [");
    b.append("         {");
    b.append("          \"kind\": \"param\",");
    b.append("          \"name\": \"id\",");
    b.append("          \"orig\": \"series_id\",");
    b.append("          \"reqd\": true,");
    b.append("          \"type\": \"`$STRING`\"");
    b.append("         }");
    b.append("        ]");
    b.append("       },");
    b.append("       \"kind\": \"http\",");
    b.append("       \"method\": \"GET\",");
    b.append("       \"orig\": \"/series/{series_id}\",");
    b.append("       \"parts\": [");
    b.append("        \"series\",");
    b.append("        \"{id}\"");
    b.append("       ],");
    b.append("       \"rename\": {");
    b.append("        \"param\": {");
    b.append("         \"series_id\": \"id\"");
    b.append("        }");
    b.append("       },");
    b.append("       \"segments\": [");
    b.append("        {");
    b.append("         \"lit\": \"series\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"var\": \"id\"");
    b.append("        }");
    b.append("       ],");
    b.append("       \"select\": {");
    b.append("        \"exist\": [");
    b.append("         \"id\"");
    b.append("        ]");
    b.append("       },");
    b.append("       \"transform\": {");
    b.append("        \"req\": \"`reqdata`\",");
    b.append("        \"res\": \"`body`\"");
    b.append("       }");
    b.append("      }");
    b.append("     ]");
    b.append("    }");
    b.append("   },");
    b.append("   \"relations\": {");
    b.append("    \"ancestors\": []");
    b.append("   }");
    b.append("  }");
    b.append(" }");
    b.append("}");
    return b.toString();
  }
}
